{
  config,
  lib,
  ...
}: let
  inherit (lib) types;

  cfg = config.configurations.environment;
in {
  options.configurations.environment = {
    enable = lib.mkEnableOption "user environment";
    sessionVariables = lib.mkOption {
      type = with types; attrsOf (oneOf [(listOf (oneOf [int str path])) int str path]);
      default = {};
      example = {
        EDITOR = "nvim";
        VISUAL = "nvim";
      };
      description = ''
        A set of environment variables used in the user environment.
        If a list of strings is used, they will be concatenated with colon
        characters.
      '';
    };
  };

  config =
    lib.mkIf (cfg.enable)
    (lib.mkMerge [
      (lib.mkIf (cfg.sessionVariables != {}) {
        files.".baile-env" = let
          to-env = env: lib.concatMapStringsSep ":" toString (lib.toList env);
          lines = lib.concatLines (lib.mapAttrsToList (name: value: "export ${name}=\"${to-env value}\"") cfg.sessionVariables);
        in
          ''
            ## Generated by baile

            # This file is generated by baile.
            # Do not edit this file directly.
            # Instead, edit the configuration in `config.configurations.environment.sessionVariables`.

          ''
          + lines;
      })
    ]);
}
