{
  config,
  lib,
  ...
}: let
  inherit (lib) baile types;

  cfg = config.xdg-user-dirs;
  cfg-environment = config.environment;

  xdg' = lib.filter (location: location.envVariable != null) (builtins.attrValues config.xdg);
in {
  options.xdg-user-dirs = {
    enable = lib.mkEnableOption "user dirs.";
    create = lib.mkOption {
      type = types.bool;
      default = false;
      description = "Create the XDG user directories on activation.";
    };
  };

  options.xdg = lib.mkOption {
    type = with types;
      attrsOf (types.submodule ({
        name,
        config,
        ...
      }: {
        options = {
          envVariable = lib.mkOption {
            type = with types; nullOr str;
            default = "XDG_${(lib.toUpper (lib.replaceStrings ["/" " "] ["_" "_"] name))}_DIR";
            description = "The environment variable for this XDG directory.";
            apply = v:
              if v == null
              then null
              else lib.toUpper v;
          };
        };
      }));
  };

  config = let
    dirs' =
      map (location: {
        name = location.envVariable;
        value = "$HOME/${location.path}";
      })
      xdg';
  in
    lib.mkMerge [
      {
        xdg = {
          cache.envVariable = lib.mkDefault null;
          config.envVariable = lib.mkDefault null;
          data.envVariable = lib.mkDefault null;
          state.envVariable = lib.mkDefault null;

          desktop.path = lib.mkDefault "Desktop";
          documents.path = lib.mkDefault "Documents";
          download.path = lib.mkDefault "Downloads";
          music.path = lib.mkDefault "Music";
          pictures.path = lib.mkDefault "Pictures";
          publicshare.path = lib.mkDefault "Public";
          templates.path = lib.mkDefault "Templates";
          videos.path = lib.mkDefault "Videos";
          wallpapers.path = lib.mkDefault "${config.xdg.pictures.path}/Wallpapers";
          screenshots.path = lib.mkDefault "${config.xdg.pictures.path}/Screenshots";
        };
      }
      (lib.mkIf (cfg.enable) {
        environment.sessionVariables = lib.listToAttrs dirs';
        programs.xdg-user-dirs.enable = lib.mkDefault true;
        xdg.config.files = let
          entries = map (location: ''${location.name}="${location.value}"'') dirs';
        in {
          "user-dirs.dirs" = ''
            # Generated by baile
            ${lib.concatStringsSep "\n" entries}
          '';

          "user-dirs.conf" = ''
            # Generated by baile
            enabled=False
          '';
        };
        environment.activation.dag = lib.mkIf cfg.create {
          create-xdg-user-dirs = let
            cmds = map (location: let path = "${cfg-environment.home}/${location.path}"; in ''[[ -e "${path}" ]] || mkdir -p "${path}"'') xdg';
          in
            baile.dag.entryAfter ["activate-files"] cmds;
        };
      })
    ];
}
